### ISSUE TITLE
It is not possible to install the nodes in Node Red on Raspbian Buster.

### ISSUE THREAD

**Issue by Antonio-SeGa** [O-Hahn/node-red-contrib-grovepi#5]
make: *** [buffertools.target.mk:107: Release/obj.target/buffertools/buffertools.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/buffertools/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:314:20)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.10.103-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/buffertools
gyp ERR! node -v v12.22.12
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! buffertools@2.1.6 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buffertools@2.1.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2022-07-01T23_06_56_482Z-debug.log

**Comment by s-light** [comment]
similar problem for me.

i think it is a node-version mismatch/problem..
